### PR TITLE
Allow dash in tfs uri and fixed a bug where the simple search filter wasnt retrieved from the localstorage correctly

### PR DESCRIPTION
**Pull request by WilliamRoxit**

### CODE REVIEW

**Comment by on5sl** [comment]
Dear William,

By all the small optimalizations it's hard too see what is changed were. Could you split these in multiple pull requests? One for the using optimalizations en performance change for TFS, and one for the actual fixing of the dash and another one for the search bugfix?
Please also try to avoid adding missing newlines to avoid strange text files as a result.

**Comment by WilliamRoxit** [comment]
Hi Bram,

I've tried that, but my github skills are letting me down. Maybe it is better to refresh my fork somehow and do the changes again. I couldn't find a way to pull-request a single commit, only a way to pull-request all my commits :(

I'll try to fix it the appropiate way.

**Comment by on5sl** [comment]
Pull request are always for a complete branch. I can also see you have some conflict, in order to avoid these i would do to the following:

1) pull the latest source from GitHub
2) create a different branch for each topic (bugfixsearch, bugfixdash,perfopt, etc...)
3) create for each branch a pull request

**Comment by mdb1988** [comment]
Hi WilliamRoxit, 
Thanks for the intrest & collaboration, but I'm going to close this pull request due to some merge conflicts.

If you still want, like on5sl said, you can try to:
1) pull the latest source from GitHub
2) create a different branch for each topic (bugfixsearch, bugfixdash,perfopt, etc...)
3) create for each branch a pull request

**Pull request closed without merging**
